export enum PermissionCategoriesEnum {
	ACCOUNT = "account",
	ESTABLISHMENT = "establishment",
	FEATURES = "features",
	OPTION_FEATURES = "option_features",
	OPTIONS = "options",
	ORGANIZATION = "organization",
	PERMISSIONS = "permissions",
	PLAN_FEATURES = "plan_features",
	PLAN_OPTION_FEATURES = "plan_option_features",
	PLANS = "plans",
	PROMO_CODES = "promo_codes",
	ROLE_PERMISSIONS = "role_permissions",
	ROLES = "roles",
	SUBSCRIPTION = "subscription",
	TEAMS = "teams",
	USER_ESTABLISHMENT_ROLES = "user_establishment_roles",
	USER_PERMISSIONS = "user_permissions",
	USERS = "users",
}
