export enum UserRoleEnum {
	CLIENT = "CLIENT",
	ORGANIZATION_EMPLOYEE = "ORGANIZATION_EMPLOYEE",
	ORGANIZATION_ADMIN = "ORGANIZATION_ADMIN",
	ORGANIZATION_SUPER_ADMIN = "SUPER_ADMIN",
	ORGANIZATION_OWNER = "ORGANIZATION_OWNER",
	BOOKER_EMPLOYEE = "BOOKER_EMPLOYEE",
	BOOKER_ADMIN = "BOOKER_ADMIN",
	BOOKER_SUPER_ADMIN = "BOOKER_SUPER_ADMIN",
	BOOKER_OWNER = "BOOKER_OWNER",
}
