enum UserRoleEnum {
	CLIENT = "CLIENT",
	EMPLOYEE = "EMPLOYEE",
	ADMIN = "ADMIN",
	SUPER_ADMIN = "SUPER_ADMIN",
	BRAINST_EMPLOYEE = "BRAINST_EMPLOYEE",
	BRAINST_ADMIN = "BRAINST_ADMIN",
	BRAINST_SUPER_ADMIN = "BRAINST_SUPER_ADMIN",
}

export default UserRoleEnum;
