enum UserStatusEnum {
	ACTIVE = "ACTIVE",
	INACTIVE = "INACTIVE",
	SUSPENDED = "SUSPENDED",
	BANNED = "BANNED",
	NOT_VERIFIED = "NOT_VERIFIED",
	VERIFIED = "VERIFIED",
	CREATE_PASSWORD = "CREATE_PASSWORD",
	ARCHIVED = "ARCHIVED",
}

export default UserStatusEnum;
